graph LR
  Hub--> Dashboard

  subgraph "JS-Client"

    JS --> Log[Log-Only Mode]
    subgraph soon["soon*"]
    JS --> App-Overlay
    end
  end
  JS[JS-Client Library] --> Hub{Hub}

  CS[CSharp] --> Hub


class soon lightblue;
classDef lightblue fill:#23D;
classDef lightblue color: white;
classDef lightblue padding-top: 10px;
